#spring:
#  application:
#    name: factory-end
#  jpa:
#    hibernate:
##      ddl-auto: update
#    show-sql: true
#
#  datasource:
#    #主数据源
#    primary:
#      jdbc-url: jdbc:sqlserver://192.168.122.30;databaseName=Factory1
#      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
#      username: sa
#      password: 1234
#    #次数据源
#    secondary:
#      jdbc-url: jdbc:sqlserver://localhost;databaseName=SA1
#      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
#      username: sa
#      password: 123456
##  jooq:
##    sql-dialect: org.hibernate.dialect.SQLServer2016Dialect
#
##spring.jpa.hibernate.dialect=org.hibernate.dialect.SQLServer2016Dialect


#mqtt:
#  username: admin
#  password: password
#  host-url: tcp://127.0.0.1:61613		# 你自己服务器的地址和端口，这个需要改
#  clientID: test1							# 这个改不改随意，但不同的客户端肯定不能一样
#  default-topic: response						# 订阅设备的响应主题
#  timeout: 100
#  keepalive: 100
#  target-topic: request           #写数据的主题
